package objects.block;

import audio.SoundType;
import graphics.Texture;
import graphics.VariantTextureMaker;
import graphics.ligth.*;
import graphics.shape.*;
import objects.block.blockBehavior.*;
import objects.block.blockBehavior.logic.*;
import objects.collision.*;
import objects.property.*;
import tools.PathManager;

public enum BlockTemplate {
        /* 0 */
        BLUE_BLOCK(VariantTextureMaker.createBlockType("blueBlock", "blue-block.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        RED_BLOCK(VariantTextureMaker.createBlockType("redBlock", "red-block.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        PURPLE_BLOCK(VariantTextureMaker.createBlockType("purpleBlock", "purple-block.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        FIRE_CAMP(new BlockType("fireCamp",
                        new Texture[] {
                                        Texture.createBasicTexture(ShapeList.TRANSPARENT_CUBE,
                                                        new String[] { "fire-camp/fire-0.png", "fire-camp/fire-1.png", "fire-camp/fire-2.png" }, 
                                                        2) },
                        null,
                        new Property[] { new PropertyLight(
                                        new LightSource(new ColorRGB(1, 0.6, 0.2), 1.2, 0.8, 0.1)),
                                        new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.FIRE) },
                        new BlockBehavior[] { new BlockBehaviorBlazable() })),
        BLUE_STAIRS_RIGHT(new BlockType("blueStairsRight",
                        new Texture[] { new Texture(ShapeList.STAIR2, PathManager.loadImage("blue-stairs-right.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        /* 5 */
        LAVA(new BlockType("lava",
                        new Texture[] {
                                        Texture.createBasicTexture(ShapeList.RECTANGLE1,
                                                        new String[] { "lava/lava-1-0.png", "lava/lava-1-1.png",
                                                                        "lava/lava-1-2.png",
                                                                        "lava/lava-1-3.png" },
                                                        5),
                                        Texture.createBasicTexture(ShapeList.RECTANGLE2,
                                                        new String[] { "lava/lava-2-0.png", "lava/lava-2-1.png",
                                                                        "lava/lava-2-2.png",
                                                                        "lava/lava-2-3.png" },
                                                        5),
                                        Texture.createBasicTexture(ShapeList.RECTANGLE3,
                                                        new String[] { "lava/lava-3-0.png", "lava/lava-3-1.png",
                                                                        "lava/lava-3-2.png",
                                                                        "lava/lava-3-3.png" },
                                                        5),
                                        Texture.createBasicTexture(
                                                        new String[] { "lava/lava-4-0.png", "lava/lava-4-1.png",
                                                                        "lava/lava-4-2.png", "lava/lava-4-3.png" },
                                                        5) },
                        new Collision[] { CollisionList.RECTANGLE1, CollisionList.RECTANGLE2, CollisionList.RECTANGLE3,
                                        CollisionList.CUBE },
                        new Property[] {
                                        new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.LAVA),
                                        new PropertyLight(new LightSource(new ColorRGB(1, 0.6, 0.4), 1.5, 0.5, 0.15)) },
                        new BlockBehavior[] { new BlockBehaviorLiquid(4, 6),
                                        new BlockBehaviorKill(),
                                        new BlockBehaviorApplyForce(0, 0, 0.4),
                                        new BlockBehaviorBlazable() })),
        SUN(new BlockType("sun",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION),
                                        new PropertyLight(new LightSource(new ColorRGB[] {
                                                        new ColorRGB(1, 1, 1), // plain day (white)
                                                        new ColorRGB(1, 1, 1), // (white)
                                                        new ColorRGB(1, 1, 1),
                                                        new ColorRGB(1, 1, 1),
                                                        new ColorRGB(1, 0.9, 0.75),
                                                        new ColorRGB(1, 0.5, 0.3), // evening (orange-pink)
                                                        new ColorRGB(0.6, 0.3, 0.35),
                                                        new ColorRGB(0.2, 0.2, 0.4), // night (low blue-white)
                                                        new ColorRGB(0.2, 0.2, 0.4),
                                                        new ColorRGB(0.2, 0.2, 0.4),
                                                        new ColorRGB(0.2, 0.2, 0.4),
                                                        new ColorRGB(0.6, 0.3, 0.35),
                                                        new ColorRGB(0.8, 0.3, 0.3), // morning (reddish)
                                                        new ColorRGB(1, 0.9, 0.75),
                                        }, 1500, 0.75, 1, 0)) },
                        null)),

        GLASS(new BlockType("glassBlock", 
                new Texture[] { new Texture(ShapeList.TRANSPARENT_CUBE, PathManager.loadImage("glass-block.png")) },
                null
        )),

        DIRT(new BlockType("dirtBlock", "dirt.png")),
        GRASS(new BlockType("grassBlock", "grass.png")),
        /* 10 */
        HEDGE(new BlockType("hedge", "hedge.png",
                null,
                new Property[] { new Property(PropertyList.BURNABLE) },
                null
        )),
        LEVER(new BlockType("lever",
                        new Texture[] { new Texture(ShapeList.LEVER_OFF, PathManager.loadImage("lever/lever-F.png")),
                                        new Texture(ShapeList.LEVER_ON, PathManager.loadImage("lever/lever-T.png")) },
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] {
                                        new BlockBehaviorLever()
                        })),
        WORLD(new BlockType("worldBlock",
                        new Texture[] {
                                        new Texture(ShapeList.CUBE,
                                                        PathManager.loadImage("world-loader/world-loader-0.png")),
                                        Texture.createBasicTexture(
                                                        new String[] { "world-loader/world-loader-1-0.png",
                                                                        "world-loader/world-loader-1-1.png",
                                                                        "world-loader/world-loader-1-2.png" },
                                                        3)

                        },
                        new Property[] { new PropertyLight(new LightSource(new ColorRGB(0, 1, 1), 0.7, 0.7, 0)) },
                        new BlockBehavior[] { new BlockBehaviorChangeWorld(),
                                        new BlockBehaviorActivableProperty(PropertyLight.NAME)
                        })),
        NEW_WORLD(new BlockType("newWorldBlock",
                        new Texture[] {
                                        new Texture(ShapeList.CUBE,
                                                        PathManager.loadImage("world-loader/world-loader-0.png")),
                                        Texture.createBasicTexture(
                                                        new String[] { "world-loader/world-loader-1-0.png",
                                                                        "world-loader/world-loader-1-1.png",
                                                                        "world-loader/world-loader-1-2.png" },
                                                        3)

                        },
                        new Property[] { new PropertyLight(new LightSource(new ColorRGB(0, 1, 1), 0.7, 0.7, 0)) },
                        new BlockBehavior[] { new BlockBehaviorNewWorld(),
                                        new BlockBehaviorActivableProperty(PropertyLight.NAME)
                        })),
        RED_CARPET(new BlockType("redCarpet", "red-carpet-block.png")),
        /* 15 */
        RED_GOLDEN_CARPET(new BlockType("redGoldenCarpet", "red-golden-carpet-block.png")),
        RED_GOLDEN_CARPET2(new BlockType("redGoldenCarpet2", "red-golden-carpet-2-block.png")),
        RED_GOLDEN_CARPET3(new BlockType("redGoldenCarpet3", "red-golden-carpet-3-block.png")),
        LEAVES(new BlockType("leaves", "leaves.png",
        null,
                new Property[] { new Property(PropertyList.BURNABLE) },
                null
        )),
        SAND(new BlockType("sand", "sand-block.png")),
        /* 20 */
        PINE_LOG(VariantTextureMaker.createBlockType("pineLog", "wood/pine-log.png", ShapeList.COLUMN)),
        BLOCK(VariantTextureMaker.createBlockType("block", "block.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        TRAY(new BlockType("blockTray", "block-tray.png")),
        BRICK1(new BlockType("blockBrick1", "block-brick-1.png")),
        BRICK2(new BlockType("blockBrick2", "block-brick-2.png")),
        /* 25 */
        BROKEN(new BlockType("blockBroken", "block-broken.png",
                        null,
                        new Property[] { new Property(PropertyList.DESTRUCTIBLE)},
                        null
        )),
        BLOCK_COLUMN_MOSSY(VariantTextureMaker.createBlockType("blockColumnMossy", "block-column-mossy.png", ShapeList.COLUMN)),
        BLOCK_COLUMN(VariantTextureMaker.createBlockType("blockColumn", "block-column.png", ShapeList.COLUMN)),
        HALF_GRASS1(new BlockType("blockHalfGrass1", "block-half-grass-1.png")),
        HALF_GRASS2(new BlockType("blockHalfGrass2", "block-half-grass-2.png")),
        /* 30 */
        HALF_GRASS3(new BlockType("blockHalfGrass3", "block-half-grass-3.png")),
        HALF_GRASS4(new BlockType("blockHalfGrass4", "block-half-grass-4.png")),
        HALF_HORIZONTAL1(new BlockType("blockHalfHorizontal1",
                        new Texture[] { new Texture(ShapeList.RECTANGLE2,
                                        PathManager.loadImage("block-half-horizontal-1.png")) },
                        new Collision[] { CollisionList.SLAB_BOTTOM },
                        null,
                        null)),
        HALF_HORIZONTAL2(new BlockType("blockHalfHorizontal2",
                        new Texture[] { new Texture(ShapeList.SLAB_TOP,
                                        PathManager.loadImage("block-half-horizontal-2.png")) },
                        new Collision[] { CollisionList.SLAB_TOP },
                        null,
                        null)),
        HALF_VERTICAL1(new BlockType("blockHalfVertical1",
                        new Texture[] { new Texture(ShapeList.SLAB_VERTICAL1,
                                        PathManager.loadImage("block-half-vertical-1.png")) },
                        new Collision[] { CollisionList.SLAB_VERTICAL1 },
                        null,
                        null)),
        /* 35 */
        HALF_VERTICAL2(new BlockType("blockHalfVertical2",
                        new Texture[] { new Texture(ShapeList.SLAB_VERTICAL2,
                                        PathManager.loadImage("block-half-vertical-2.png")) },
                        new Collision[] { CollisionList.SLAB_VERTICAL2 },
                        null,
                        null)),
        HALF_VERTICAL3(new BlockType("blockHalfVertical3",
                        new Texture[] { new Texture(ShapeList.SLAB_VERTICAL3,
                                        PathManager.loadImage("block-half-vertical-3.png")) },
                        new Collision[] { CollisionList.SLAB_VERTICAL3 },
                        null,
                        null)),
        HALF_VERTICAL4(new BlockType("blockHalfVertical4",
                        new Texture[] { new Texture(ShapeList.SLAB_VERTICAL4,
                                        PathManager.loadImage("block-half-vertical-4.png")) },
                        new Collision[] { CollisionList.SLAB_VERTICAL4 },
                        null,
                        null)),
        HOLE1(new BlockType("blockHole1", "block-hole-1.png")),
        HOLE2(new BlockType("blockHole2", "block-hole-2.png")),
        /* 40 */
        LINES(new BlockType("blockLines", "block-lines.png")),
        MOSSY1(VariantTextureMaker.createBlockType("blockMossy1", "block-mossy-1.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        MOSSY2(VariantTextureMaker.createBlockType("blockMossy2", "block-mossy-2.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        SLOPE_HALF1(new BlockType("blockSlopeHalf1",
                        new Texture[] { new Texture(ShapeList.SLOPE_HALF1,
                                        PathManager.loadImage("blockSlopes/block-slope-half1.png")) },
                        new Collision[] { CollisionList.STAIR_HALF1 },
                        null,
                        null)),
        SLOPE_HALF2(new BlockType("blockSlopeHalf2",
                        new Texture[] { new Texture(ShapeList.SLOPE_HALF2,
                                        PathManager.loadImage("blockSlopes/block-slope-half2.png")) },
                        new Collision[] { CollisionList.STAIR_HALF2 },
                        null,
                        null)),
        /* 45 */
        SLOPE_HALF3(new BlockType("blockSlopeHalf3",
                        new Texture[] { new Texture(ShapeList.SLOPE_HALF3,
                                        PathManager.loadImage("blockSlopes/block-slope-half3.png")) },
                        new Collision[] { CollisionList.STAIR_HALF3 },
                        null,
                        null)),
        SLOPE_HALF4(new BlockType("blockSlopeHalf4",
                        new Texture[] { new Texture(ShapeList.SLOPE_HALF4,
                                        PathManager.loadImage("blockSlopes/block-slope-half4.png")) },
                        new Collision[] { CollisionList.STAIR_HALF4 },
                        null,
                        null)),
        STAIRS_LEFT_MOSSY(new BlockType("blockStairsLeftMossy",
                        new Texture[] { new Texture(ShapeList.STAIR1,
                                        PathManager.loadImage("block-stairs-left-mossy.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        STAIRS_RIGHT_MOSSY(new BlockType("blockStairsRightMossy",
                        new Texture[] { new Texture(ShapeList.STAIR2,
                                        PathManager.loadImage("block-stairs-right-mossy.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        STAIRS_LEFT(new BlockType("blockStairs1",
                        new Texture[] { new Texture(ShapeList.STAIR1,
                                        PathManager.loadImage("blockStairs/block-stairs1.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        /* 50 */
        STAIRS_RIGHT(new BlockType("blockStairs2",
                        new Texture[] { new Texture(ShapeList.STAIR2,
                                        PathManager.loadImage("blockStairs/block-stairs2.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        GRASS_HALF_SLAB_1(new BlockType("grassHalfSlab1", "grass-half-slab-1.png")),
        GRASS_HALF_SLAB_2(new BlockType("grassHalfSlab2", "grass-half-slab-2.png")),
        GRASS_SLAB(new BlockType("grassSlab", "grass-slab.png")),
        GRASS_SLABS(new BlockType("grassSlabs", "grass-slabs.png")),
        /* 55 */
        BLOCK_GRASS_CORNER_OUT_LEFT(new BlockType("blockGrassCornerOuterLeft", "block-grass-corner-outer-left.png")),
        BLOCK_GRASS_CORNER_OUT_RIGHT(new BlockType("blockGrassCornerOuterRight", "block-grass-corner-outer-right.png")),
        BLOCK_GRASS_CORNER_OUT_TOP(new BlockType("blockGrassCornerOuterTop", "block-grass-corner-outer-top.png")),
        BLOCK_GRASS_CORNER_OUT_BOTTOM(
                        new BlockType("blockGrassCornerOuterBottom", "block-grass-corner-outer-bottom.png")),
        BLOCK_GRASS_CORNER_IN_LEFT(new BlockType("blockGrassCornerInnerLeft", "block-grass-corner-inner-left.png")),
        /* 60 */
        BLOCK_GRASS_CORNER_IN_RIGHT(new BlockType("blockGrassCornerInnerRight", "block-grass-corner-inner-right.png")),
        BLOCK_GRASS_CORNER_IN_TOP(new BlockType("blockGrassCornerInnerTop", "block-grass-corner-inner-top.png")),
        BLOCK_GRASS_CORNER_IN_BOTTOM(
                        new BlockType("blockGrassCornerInnerBottom", "block-grass-corner-inner-bottom.png")),
        GRASS_HALF_SLAB_3(new BlockType("GrassHalfSlab3", "grass-half-slab-3.png")),
        GRASS_HALF_SLAB_4(new BlockType("GrassHalfSlab4", "grass-half-slab-4.png")),
        /* 65 */
        BLOCK_FLOWER(new BlockType("blockFlower", "block-flower.png")),
        BLOCK_CLUBS(new BlockType("blockClubs", "block-clubs.png")),
        BLOCK_ALTERNATE(new BlockType("blockAlternate", "block-alternate.png")),
        TELEPORTER(new BlockType("teleporter",
                        new Texture[] { new Texture(ShapeList.CUBE,
                                        PathManager.loadImage("teleporter/teleporter-F.png")),
                                        Texture.createBasicTexture(
                                                        new String[] { "teleporter/teleporter-0-T.png",
                                                                        "teleporter/teleporter-1-T.png",
                                                                        "teleporter/teleporter-2-T.png",
                                                                        "teleporter/teleporter-3-T.png" },
                                                        3) },
                        null,
                        new Property[] { new PropertyLight(
                                        new LightSource(new ColorRGB(0.8, 0.2, 0.7), 0.35, 0.5, 0.05)) },
                        new BlockBehavior[] { new BlockBehaviorTeleportation(),
                                        new BlockBehaviorActivableProperty(PropertyLight.NAME) })),
        BLACK_BLOCK(new BlockType("blackBlock", "black-block.png")),
        /* 70 */
        BLUE_BLOCK_BROKEN(new BlockType("blueBlockBroken", "blue-block-broken.png")),
        BLUE_BLOCK_CLUBS(new BlockType("blueBlockClubs", "blue-block-clubs.png")),
        BLUE_BLOCK_COLUMN(VariantTextureMaker.createBlockType("blueBlockColumn", "blue-block-column.png", ShapeList.COLUMN)),
        BLUE_BLOCK_RAYS(new BlockType("blueBlockRays", "blue-block-rays.png")),
        BOOK_SHELVE_1(new BlockType("bookShelve1", "book-shelve-1.png")),
        /* 75 */
        BOOK_SHELVE_2(new BlockType("bookShelve2", "book-shelve-2.png")),
        BROWN_BLOCK(VariantTextureMaker.createBlockType("brownBlock", "brown-block.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        DISTORTED_BLOCK_BLUE(new BlockType("distortedBlockBlue", "distorted-block-blue.png")),
        DISTORTED_BLOCK_GREEN(new BlockType("distortedBlockGreen", "distorted-block-green.png")),
        DISTORTED_BLOCK_ORANGE(new BlockType("distortedBlockOrange", "distorted-block-orange.png")),
        /* 80 */
        DISTORTED_BLOCK_PURPLE(new BlockType("distortedBlockPurple", "distorted-block-purple.png")),
        DISTORTED_BLOCK_RED(new BlockType("distortedBlockRed", "distorted-block-red.png")),
        DISTORTED_BLOCK_YELLOW(new BlockType("distortedBlockYellow", "distorted-block-yellow.png")),
        GRAVEL_DARK(new BlockType("gravelDark", "gravel-dark.png")),
        GRAVEL(new BlockType("gravel", "gravel.png")),
        /* 85 */
        GREEN_BLOCK(VariantTextureMaker.createBlockType("greenBlock", "green-block.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        SHELVE(new BlockType("shelve",
                new Texture[] { new Texture(ShapeList.TRANSPARENT_CUBE, PathManager.loadImage("shelve.png")) },
                null
        )),
        STONE_BROKEN(new BlockType("stoneBroken", "stone-broken.png")),
        BRAZIER(new BlockType("brazier",
                        new Texture[] {
                                        Texture.createBasicTexture(ShapeList.TRANSPARENT_CUBE,
                                                        new String[] { "brazier/fire-0.png", "brazier/fire-1.png", "brazier/fire-2.png" }, 
                                                        2) },
                        new Collision[] {CollisionList.COLUMN},
                        new Property[] { new PropertyLight(
                                        new LightSource(new ColorRGB(1, 0.6, 0.2), 1.2, 0.8, 0.1)),
                                        new PropertySound(SoundType.FIRE) },
                        new BlockBehavior[] { new BlockBehaviorBlazable() })),
        STONE_MOSSY(VariantTextureMaker.createBlockType("stoneMossy", "stone-mossy.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        /* 90 */
        STONE_POLISHED(new BlockType("stonePolished", "stone-polished.png")),
        STONE(VariantTextureMaker.createBlockType("stone", "stone.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        WHITE_BLOCK(VariantTextureMaker.createBlockType("whiteBlock", "white-block.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        WOOD_ACACIA(VariantTextureMaker.createBlockType("woodAcacia", "wood/wood-acacia.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BARRIERS, ShapeList.SLABS)),
        WOOD_OAK(VariantTextureMaker.createBlockType("woodOak", "wood/wood-oak.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BARRIERS, ShapeList.SLABS)),
        /* 95 */
        WOOD_PINE(VariantTextureMaker.createBlockType("woodPine", "wood/wood-pine.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BARRIERS, ShapeList.SLABS)),
        ICE(new BlockType("ice", "ice.png") {
                {
                        setOpacity(0.5);
                        setAdherency(0.01);
                }
        }),
        SNOW(new BlockType("snow", "snow.png")),
        PRESSURE_PLATE(new BlockType("pressurePlate",
                        new Texture[] { Texture.createBasicTexture("pressure-plate-F.png"),
                                        Texture.createBasicTexture("pressure-plate-T.png") },
                        null,
                        new Property[] { new PropertyLight(new LightSource(new ColorRGB(1, 0.6, 0.4), 0.2, 0.5, 0)) },
                        new BlockBehavior[] { new BlockBehaviorPressurePlate(),
                                        new BlockBehaviorActivableProperty(PropertyLight.NAME) })),
        STAINED_GLASS_RED_LEFT(new BlockType("stainedGlassRedLeft",
                        new Texture[] { new Texture(ShapeList.BORDER_LEFT,
                                        PathManager.loadImage("stained-glass/stained-glass-red-left.png")) },
                        new Collision[] { CollisionList.BARRIER_LEFT },
                        null,
                        null) {
                {
                        setColor(new ColorRGB(1, 0, 0));
                        setOpacity(0.1);
                        setAllowLight(Face.RIGHT.index,true);
                }
        }),
        /* 100 */
        STAINED_GLASS_RED_RIGHT(new BlockType("stainedGlassRedRight",
                        new Texture[] { new Texture(ShapeList.BORDER_RIGHT,
                                        PathManager.loadImage("stained-glass/stained-glass-red-right.png")) },
                        new Collision[] { CollisionList.BARRIER_RIGHT },
                        null,
                        null) {
                {
                        setColor(new ColorRGB(1, 0, 0));
                        setOpacity(0.1);
                        setAllowLight(Face.LEFT.index,true);
                }
        }),
        STAINED_GLASS_BLUE_LEFT(new BlockType("stainedGlassBlueLeft",
                        new Texture[] { new Texture(ShapeList.BORDER_LEFT,
                                        PathManager.loadImage("stained-glass/stained-glass-blue-left.png")) },
                        new Collision[] { CollisionList.BARRIER_LEFT },
                        null,
                        null) {
                {
                        setColor(new ColorRGB(0, 0, 1));
                        setOpacity(0.1);
                        setAllowLight(Face.RIGHT.index,true);
                }
        }),
        STAINED_GLASS_BLUE_RIGHT(new BlockType("stainedGlassBlueRight",
                        new Texture[] { new Texture(ShapeList.BORDER_RIGHT,
                                        PathManager.loadImage("stained-glass/stained-glass-blue-right.png")) },
                        new Collision[] { CollisionList.BARRIER_RIGHT },
                        null,
                        null) {
                {
                        setColor(new ColorRGB(0, 0, 1));
                        setOpacity(0.1);
                        setAllowLight(Face.LEFT.index,true);
                }
        }),
        STAINED_GLASS_GREEN_LEFT(new BlockType("stainedGlassGreenLeft",
                        new Texture[] {
                                        new Texture(ShapeList.BORDER_LEFT,
                                                        PathManager.loadImage(
                                                                        "stained-glass/stained-glass-green-left.png")) },
                        new Collision[] { CollisionList.BARRIER_LEFT },
                        null,
                        null) {
                {
                        setColor(new ColorRGB(0, 1, 0));
                        setOpacity(0.1);
                        setAllowLight(Face.RIGHT.index,true);
                }
        }),
        STAINED_GLASS_GREEN_RIGHT(new BlockType("stainedGlassGreenRight",
                        new Texture[] {
                                        new Texture(ShapeList.BORDER_RIGHT,
                                                        PathManager.loadImage(
                                                                        "stained-glass/stained-glass-green-right.png")) },
                        new Collision[] { CollisionList.BARRIER_RIGHT },
                        null,
                        null) {
                {
                        setColor(new ColorRGB(0, 1, 0));
                        setOpacity(0.1);
                        setAllowLight(Face.LEFT.index,true);
                }
        }),
        /* 105 */
        SUNLIGHT(new BlockType("sunlight",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION),
                                        new PropertyLight(new LightSource(new ColorRGB[] {
                                                        new ColorRGB(1, 1, 1), // plain day (white)
                                                        new ColorRGB(1, 1, 1), // (white)
                                                        new ColorRGB(1, 1, 1),
                                                        new ColorRGB(1, 1, 1),
                                                        new ColorRGB(1, 0.9, 0.75),
                                                        new ColorRGB(1, 0.5, 0.3), // evening (orange-pink)
                                                        new ColorRGB(0.6, 0.3, 0.35),
                                                        new ColorRGB(0.2, 0.2, 0.4), // night (low blue-white)
                                                        new ColorRGB(0.2, 0.2, 0.4),
                                                        new ColorRGB(0.2, 0.2, 0.4),
                                                        new ColorRGB(0.2, 0.2, 0.4),
                                                        new ColorRGB(0.6, 0.3, 0.35),
                                                        new ColorRGB(0.8, 0.3, 0.3), // morning (reddish)
                                                        new ColorRGB(1, 0.9, 0.75),
                                        }, 1200, 1, 0.9, 0)) },
                        null)),
        LINKED_LEVER(new BlockType("linkedLever",
                        new Texture[] { new Texture(ShapeList.LEVER_OFF,
                                        PathManager.loadImage("linkedLever/linked-lever-F.png")),
                                        new Texture(ShapeList.LEVER_ON,
                                                        PathManager.loadImage("linkedLever/linked-lever-T.png")) },
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] { new BlockBehaviorLever(), new BlockBehaviorActivable() })),
        WATER(new BlockType("water",
                        new Texture[] {
                                        Texture.createBasicTexture(ShapeList.RECTANGLE1,
                                                        new String[] { "water/water-1-0.png", "water/water-1-1.png",
                                                                        "water/water-1-2.png" },
                                                        5),
                                        Texture.createBasicTexture(ShapeList.RECTANGLE2,
                                                        new String[] { "water/water-2-0.png", "water/water-2-1.png",
                                                                        "water/water-2-2.png" },
                                                        5),
                                        Texture.createBasicTexture(ShapeList.RECTANGLE3,
                                                        new String[] { "water/water-3-0.png", "water/water-3-1.png",
                                                                        "water/water-3-2.png" },
                                                        5),
                                        Texture.createBasicTexture(
                                                        new String[] { "water/water-4-0.png", "water/water-4-1.png",
                                                                        "water/water-4-2.png" },
                                                        5) },
                        new Collision[] { CollisionList.RECTANGLE1, CollisionList.RECTANGLE2, CollisionList.RECTANGLE3,
                                        CollisionList.CUBE },
                        new Property[] {
                                        new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.WATER) },
                        new BlockBehavior[] { new BlockBehaviorLiquid(4, 2),
                                        new BlockBehaviorApplyForce(0, 0, 0.4) })),
        AND(new BlockType("and",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] { new BlockBehaviorAnd() })),
        OR(new BlockType("or",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] { new BlockBehaviorOr() })),
        /* 110 */
        NOT(new BlockType("not",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] { new BlockBehaviorNot() })),
        DELAY(new BlockType("delay",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] { new BlockBehaviorDelay() })),
        LOOP(new BlockType("loop",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] { new BlockBehaviorLoop() })),
        AMBIENT1(new BlockType("ambient1",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.AMBIENT1) },
                        null)),
        STAIRS3(new BlockType("blockStairs3",
                        new Texture[] { new Texture(ShapeList.STAIR3,
                                        PathManager.loadImage("blockStairs/block-stairs3.png")) },
                        new Collision[] { CollisionList.STAIR3 },
                        null,
                        null)),
        /* 115 */
        STAIRS4(new BlockType("blockStairs4",
                        new Texture[] { new Texture(ShapeList.STAIR4,
                                        PathManager.loadImage("blockStairs/block-stairs4.png")) },
                        new Collision[] { CollisionList.STAIR4 },
                        null,
                        null)),
        STAIRS_ANGLE1(new BlockType("blockStairsAngle1",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE1,
                                        PathManager.loadImage("blockStairs/block-stairs-angle1.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE1 },
                        null,
                        null)),
        STAIRS_ANGLE2(new BlockType("blockStairsAngle2",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE2,
                                        PathManager.loadImage("blockStairs/block-stairs-angle2.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE2 },
                        null,
                        null)),
        STAIRS_ANGLE3(new BlockType("blockStairsAngle3",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE3,
                                        PathManager.loadImage("blockStairs/block-stairs-angle3.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE3 },
                        null,
                        null)),
        STAIRS_ANGLE4(new BlockType("blockStairsAngle4",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE4,
                                        PathManager.loadImage("blockStairs/block-stairs-angle4.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE4 },
                        null,
                        null)),
        /* 120 */
        STAIRS_ANGLE5(new BlockType("blockStairsAngle5",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE5,
                                        PathManager.loadImage("blockStairs/block-stairs-angle5.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE5 },
                        null,
                        null)),
        STAIRS_ANGLE6(new BlockType("blockStairsAngle6",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE6,
                                        PathManager.loadImage("blockStairs/block-stairs-angle6.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE6 },
                        null,
                        null)),
        STAIRS_ANGLE7(new BlockType("blockStairsAngle7",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE7,
                                        PathManager.loadImage("blockStairs/block-stairs-angle7.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE7 },
                        null,
                        null)),
        STAIRS_ANGLE8(new BlockType("blockStairsAngle8",
                        new Texture[] { new Texture(ShapeList.STAIR_ANGLE8,
                                        PathManager.loadImage("blockStairs/block-stairs-angle8.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE8 },
                        null,
                        null)),

        SIGN_LEFT(new BlockType("SignLeft",
                        new Texture[] { new Texture(ShapeList.SIGN_LEFT, PathManager.loadImage("sign-left.png")) },
                        null,
                        null,
                        new BlockBehavior[] { new BlockBehaviorText() })),
        /* 125 */
        SIGN_RIGHT(new BlockType("SignRight",
                        new Texture[] { new Texture(ShapeList.SIGN_RIGHT, PathManager.loadImage("sign-right.png")) },
                        null,
                        null,
                        new BlockBehavior[] { new BlockBehaviorText() })),
        AMBIENT2(new BlockType("ambient2",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.AMBIENT2) },
                        null)),
        BACKGROUND_NATURE(new BlockType("backgroundNature",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.BACKGROUND_NATURE) },
                        null)),
        FLOWERS(new BlockType("flowers",
                        new Texture[] { new Texture(ShapeList.FLOWERS, PathManager.loadImage("herbs/flowers.png")) },
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION), new Property("floor") },
                        null)),
        GRASS_BIG(new BlockType("grassBig",
                        new Texture[] { new Texture(ShapeList.GRASS_BIG,
                                        PathManager.loadImage("herbs/grass-big.png")) },
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION), new Property("floor") },
                        null)),
        /* 130 */
        GRASS_SMALL(new BlockType("grassSmall",
                        new Texture[] { new Texture(ShapeList.GRASS_SMALL,
                                        PathManager.loadImage("herbs/grass-small.png")) },
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION), new Property("floor") },
                        null)),
        WATER_FAKE(new BlockType("waterFake",
                        new Texture[] {
                                        Texture.createBasicTexture(ShapeList.RECTANGLE3,
                                                        new String[] { "water/water-3-0.png", "water/water-3-1.png",
                                                                        "water/water-3-2.png" },
                                                        5) },
                        new Collision[] { CollisionList.RECTANGLE3 },
                        new Property[] {
                                        new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.WATER) },
                        new BlockBehavior[] {
                                        new BlockBehaviorApplyForce(0, 0, 0.4) })),
        LAVA_FAKE(new BlockType("lavaFake",
                        new Texture[] {
                                        Texture.createBasicTexture(ShapeList.RECTANGLE3,
                                                        new String[] { "lava/lava-3-0.png", "lava/lava-3-1.png",
                                                                        "lava/lava-3-2.png",
                                                                        "lava/lava-3-3.png" },
                                                        5) },
                        new Collision[] { CollisionList.RECTANGLE3 },
                        new Property[] {
                                        new Property(PropertyList.NO_COLLISION),
                                        new PropertySound(SoundType.LAVA),
                                        new PropertyLight(new LightSource(new ColorRGB(1, 0.6, 0.4), 1.5, 0.5, 0.15)) },
                        new BlockBehavior[] {
                                        new BlockBehaviorKill(),
                                        new BlockBehaviorApplyForce(0, 0, 0.4),
                                        new BlockBehaviorBlazable() })),
        SLOPE1(new BlockType("blockSlope1",
                        new Texture[] { new Texture(ShapeList.SLOPE1,
                                        PathManager.loadImage("blockSlopes/block-slope1.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        SLOPE2(new BlockType("blockSlope2",
                        new Texture[] { new Texture(ShapeList.SLOPE2,
                                        PathManager.loadImage("blockSlopes/block-slope2.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        /* 135 */
        SLOPE3(new BlockType("blockSlope3",
                        new Texture[] { new Texture(ShapeList.SLOPE3,
                                        PathManager.loadImage("blockSlopes/block-slope3.png")) },
                        new Collision[] { CollisionList.STAIR3 },
                        null,
                        null)),
        SLOPE4(new BlockType("blockSlope4",
                        new Texture[] { new Texture(ShapeList.SLOPE4,
                                        PathManager.loadImage("blockSlopes/block-slope4.png")) },
                        new Collision[] { CollisionList.STAIR4 },
                        null,
                        null)),
        SLOPE5(new BlockType("blockSlope5",
                        new Texture[] { new Texture(ShapeList.SLOPE5,
                                        PathManager.loadImage("blockSlopes/block-slope5.png")) },
                        new Collision[] { CollisionList.STAIR5 },
                        null,
                        null)),
        SLOPE6(new BlockType("blockSlope6",
                        new Texture[] { new Texture(ShapeList.SLOPE6,
                                        PathManager.loadImage("blockSlopes/block-slope6.png")) },
                        new Collision[] { CollisionList.STAIR6 },
                        null,
                        null)),
        SLOPE7(new BlockType("blockSlope7",
                        new Texture[] { new Texture(ShapeList.SLOPE7,
                                        PathManager.loadImage("blockSlopes/block-slope7.png")) },
                        new Collision[] { CollisionList.STAIR7 },
                        null,
                        null)),
        /* 140 */
        SLOPE8(new BlockType("blockSlope8",
                        new Texture[] { new Texture(ShapeList.SLOPE8,
                                        PathManager.loadImage("blockSlopes/block-slope8.png")) },
                        new Collision[] { CollisionList.STAIR8 },
                        null,
                        null)),
        SLOPE_ANGLE1(new BlockType("blockSlopeAngle1",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE1,
                                        PathManager.loadImage("blockSlopes/block-slope-angle1.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE1 },
                        null,
                        null)),
        SLOPE_ANGLE2(new BlockType("blockSlopeAngle2",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE2,
                                        PathManager.loadImage("blockSlopes/block-slope-angle2.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE2 },
                        null,
                        null)),
        SLOPE_ANGLE3(new BlockType("blockSlopeAngle3",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE3,
                                        PathManager.loadImage("blockSlopes/block-slope-angle3.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE3 },
                        null,
                        null)),
        SLOPE_ANGLE4(new BlockType("blockSlopeAngle4",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE4,
                                        PathManager.loadImage("blockSlopes/block-slope-angle4.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE4 },
                        null,
                        null)),
        /* 145 */
        SLOPE_ANGLE5(new BlockType("blockSlopeAngle5",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE5,
                                        PathManager.loadImage("blockSlopes/block-slope-angle5.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE5 },
                        null,
                        null)),
        SLOPE_ANGLE6(new BlockType("blockSlopeAngle6",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE6,
                                        PathManager.loadImage("blockSlopes/block-slope-angle6.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE6 },
                        null,
                        null)),
        SLOPE_ANGLE7(new BlockType("blockSlopeAngle7",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE7,
                                        PathManager.loadImage("blockSlopes/block-slope-angle7.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE7 },
                        null,
                        null)),
        SLOPE_ANGLE8(new BlockType("blockSlopeAngle8",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE8,
                                        PathManager.loadImage("blockSlopes/block-slope-angle8.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE8 },
                        null,
                        null)),
        ROOF_TILES_RED1(new BlockType("roofTilesRed1",
                        new Texture[] { new Texture(ShapeList.SLOPE1,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red1.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        /* 150 */
        ROOF_TILES_RED2(new BlockType("roofTilesRed2",
                        new Texture[] { new Texture(ShapeList.SLOPE2,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red2.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        ROOF_TILES_RED_ANGLE1(new BlockType("roofTilesRedAngle1",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE1,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-angle1.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE1 },
                        null,
                        null)),
        ROOF_TILES_RED_ANGLE2(new BlockType("roofTilesRedAngle2",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE2,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-angle2.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE2 },
                        null,
                        null)),
        ROOF_TILES_RED_ANGLE4(new BlockType("roofTilesRedAngle4",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE4,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-angle4.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE4 },
                        null,
                        null)),
        ROOF_TILES_RED_ANGLE5(new BlockType("roofTilesRedAngle5",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE5,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-angle5.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE5 },
                        null,
                        null)),
        /* 155 */
        ROOF_TILES_RED_ANGLE6(new BlockType("roofTilesRedAngle6",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE6,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-angle6.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE6 },
                        null,
                        null)),
        ROOF_TILES_RED_ANGLE8(new BlockType("roofTilesRedAngle8",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE8,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-angle8.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE8 },
                        null,
                        null)),
        ROOF_TILES_RED_WOOD_ANGLE1(new BlockType("roofTilesRedWoodAngle1",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE1,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-wood-angle1.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE1 },
                        null,
                        null)),
        ROOF_TILES_RED_WOOD_ANGLE2(new BlockType("roofTilesRedWoodAngle2",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE2,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-wood-angle2.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE2 },
                        null,
                        null)),
        ROOF_TILES_RED_WOOD_ANGLE4(new BlockType("roofTilesRedWoodAngle4",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE4,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-wood-angle4.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE4 },
                        null,
                        null)),
        /* 160 */
        ROOF_TILES_RED_WOOD_ANGLE5(new BlockType("roofTilesRedWoodAngle5",
                        new Texture[] { new Texture(ShapeList.SLOPE_ANGLE5,
                                        PathManager.loadImage("roofTilesRed/roof-tiles-red-wood-angle5.png")) },
                        new Collision[] { CollisionList.STAIR_ANGLE5 },
                        null,
                        null)),
        WHITE_LIGHT(new BlockType("whiteLight",
                        (Texture[]) null,
                        null,
                        new Property[] { new Property(PropertyList.NO_COLLISION),
                                        new PropertyLight(new LightSource(
                                                        new ColorRGB(1, 1, 1), 1, 0.65, 0)) },
                        null)),
        TNT(new BlockType("tnt",
                        new Texture[] { new Texture(ShapeList.CUBE,
                                        PathManager.loadImage("tnt.png")) },
                        null,
                        new Property[] {new Property(PropertyList.DESTRUCTIBLE)},
                        new BlockBehavior[] {new BlockBehaviorExploding(2.5)}
                        )),
        EXPLOSION(new BlockType("explosion",
                        new Texture[] { Texture.createBasicTexture(ShapeList.TRANSPARENT_CUBE,
                                                        new String[] { "explosion/explosion-0.png", "explosion/explosion-1.png", "explosion/explosion-2.png","explosion/explosion-3.png", "explosion/explosion-4.png", "explosion/explosion-5.png" }, 
                                                        2) },
                        null,
                        new Property[] {new Property(PropertyList.NO_COLLISION),
                                        new PropertyLight(new LightSource(
                                                new ColorRGB(1, 0.5, 0.5), 1, 0.5, 0.1))},
                        new BlockBehavior[] {new BlockBehaviorEffect(12), 
                                        new BlockBehaviorKill(),
                                        new BlockBehaviorBlazable()}
                        )),
        STONE_BARRIER_LEFT(new BlockType("stoneBarrierLeft",
                        new Texture[] { new Texture(ShapeList.BORDER_LEFT,
                                        PathManager.loadImage("stoneBarriers/stone-barrier-left.png")) },
                        new Collision[] { CollisionList.BARRIER_LEFT },
                        null,
                        null)),
        /* 165 */
        STONE_BARRIER_RIGHT(new BlockType("stoneBarrierRight",
                        new Texture[] { new Texture(ShapeList.BORDER_RIGHT,
                                        PathManager.loadImage("stoneBarriers/stone-barrier-right.png")) },
                        new Collision[] { CollisionList.BARRIER_RIGHT },
                        null,
                        null)),
        STONE_BARRIER_ANGLE1(new BlockType("stoneBarrierAngle1",
                        new Texture[] { new Texture(ShapeList.BORDER_ANGLE1,
                                        PathManager.loadImage("stoneBarriers/stone-barrier-angle1.png")) },
                        new Collision[] { CollisionList.BARRIER_ANGLE1 },
                        null,
                        null)),
        STONE_BARRIER_ANGLE2(new BlockType("stoneBarrierAngle2",
                        new Texture[] { new Texture(ShapeList.BORDER_ANGLE2,
                                        PathManager.loadImage("stoneBarriers/stone-barrier-angle2.png")) },
                        new Collision[] { CollisionList.BARRIER_ANGLE2 },
                        null,
                        null)),
        STONE_BARRIER_ANGLE3(new BlockType("stoneBarrierAngle3",
                        new Texture[] { new Texture(ShapeList.BORDER_ANGLE3,
                                        PathManager.loadImage("stoneBarriers/stone-barrier-angle3.png")) },
                        new Collision[] { CollisionList.BARRIER_ANGLE3 },
                        null,
                        null)),
        STONE_BARRIER_ANGLE4(new BlockType("stoneBarrierAngle4",
                        new Texture[] { new Texture(ShapeList.BORDER_ANGLE4,
                                        PathManager.loadImage("stoneBarriers/stone-barrier-angle4.png")) },
                        new Collision[] { CollisionList.BARRIER_ANGLE4 },
                        null,
                        null)),
        /* 170 */
        HOLDER(new BlockType("holder",
                        new Texture[] { new Texture(ShapeList.HOLDER,
                                        PathManager.loadImage("holders/holder.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        HOLDER_ROPE1(new BlockType("holderRope1",
                        new Texture[] { new Texture(ShapeList.HOLDER_ROPE1,
                                        PathManager.loadImage("holders/holder-rope1.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        HOLDER_ROPE2(new BlockType("holderRope2",
                        new Texture[] { new Texture(ShapeList.HOLDER_ROPE2,
                                        PathManager.loadImage("holders/holder-rope2.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        HOLDER_ROPE3(new BlockType("holderRope3",
                        new Texture[] { new Texture(ShapeList.HOLDER_ROPE3,
                                        PathManager.loadImage("holders/holder-rope3.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        ACACIA_HOLDER(new BlockType("acaciaHolder",
                        new Texture[] { new Texture(ShapeList.HOLDER,
                                        PathManager.loadImage("wood/woodBarriers/acacia-holder.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        /* 175 */
        ACACIA_BARRIER1(new BlockType("acaciaBarrier",
                        new Texture[] { new Texture(ShapeList.BARRIER1,
                                        PathManager.loadImage("wood/woodBarriers/acacia-barrier1.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        ACACIA_BARRIER2(new BlockType("acaciaBarrier2",
                        new Texture[] { new Texture(ShapeList.BARRIER2,
                                        PathManager.loadImage("wood/woodBarriers/acacia-barrier2.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        ACACIA_BARRIER3(new BlockType("acaciaBarrier3",
                        new Texture[] { new Texture(ShapeList.BARRIER3,
                                        PathManager.loadImage("wood/woodBarriers/acacia-barrier3.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        OAK_HOLDER(new BlockType("oakHolder",
                        new Texture[] { new Texture(ShapeList.HOLDER,
                                        PathManager.loadImage("wood/woodBarriers/oak-holder.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        OAK_BARRIER1(new BlockType("oakBarrier",
                        new Texture[] { new Texture(ShapeList.BARRIER1,
                                        PathManager.loadImage("wood/woodBarriers/oak-barrier1.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        /* 180 */
        OAK_BARRIER2(new BlockType("oakBarrier2",
                        new Texture[] { new Texture(ShapeList.BARRIER2,
                                        PathManager.loadImage("wood/woodBarriers/oak-barrier2.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        OAK_BARRIER3(new BlockType("oakBarrier3",
                        new Texture[] { new Texture(ShapeList.BARRIER3,
                                        PathManager.loadImage("wood/woodBarriers/oak-barrier3.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        PINE_HOLDER(new BlockType("pineHolder",
                        new Texture[] { new Texture(ShapeList.HOLDER,
                                        PathManager.loadImage("wood/woodBarriers/pine-holder.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        PINE_BARRIER1(new BlockType("pineBarrier",
                        new Texture[] { new Texture(ShapeList.BARRIER1,
                                        PathManager.loadImage("wood/woodBarriers/pine-barrier1.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        PINE_BARRIER2(new BlockType("pineBarrier2",
                        new Texture[] { new Texture(ShapeList.BARRIER2,
                                        PathManager.loadImage("wood/woodBarriers/pine-barrier2.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        /* 185 */
        PINE_BARRIER3(new BlockType("pineBarrier3",
                        new Texture[] { new Texture(ShapeList.BARRIER3,
                                        PathManager.loadImage("wood/woodBarriers/pine-barrier3.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        WHITE_HOLDER(new BlockType("whiteHolder",
                        new Texture[] { new Texture(ShapeList.HOLDER,
                                        PathManager.loadImage("wood/woodBarriers/white-holder.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        WHITE_BARRIER1(new BlockType("whiteBarrier",
                        new Texture[] { new Texture(ShapeList.BARRIER1,
                                        PathManager.loadImage("wood/woodBarriers/white-barrier1.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        WHITE_BARRIER2(new BlockType("whiteBarrier2",
                        new Texture[] { new Texture(ShapeList.BARRIER2,
                                        PathManager.loadImage("wood/woodBarriers/white-barrier2.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        WHITE_BARRIER3(new BlockType("whiteBarrier3",
                        new Texture[] { new Texture(ShapeList.BARRIER3,
                                        PathManager.loadImage("wood/woodBarriers/white-barrier3.png")) },
                        new Collision[] { CollisionList.POLE },
                        null,
                        null)),
        /* 190 */
        WOOD_WHITE(VariantTextureMaker.createBlockType("woodWhite", "wood/wood-white.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BARRIERS, ShapeList.SLABS)),
        WIND(new BlockType("wind",
                        new Texture[] {},
                        new Property[] { new Property(PropertyList.NO_COLLISION) },
                        new BlockBehavior[] {
                                        new BlockBehaviorApplyForce(1,0,0) })),
        BLOCK_BRICKS(VariantTextureMaker.createBlockType("blockBricks", "block-bricks.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        YELLOW_BRICKS(VariantTextureMaker.createBlockType("yellowBricks", "yellow-bricks.png", ShapeList.STAIRS, ShapeList.SLOPES, ShapeList.BORDERS, ShapeList.SLABS)),
        ACACIA_LOG(VariantTextureMaker.createBlockType("acaciaLog", "wood/acacia-log.png", ShapeList.COLUMN)),
        /* 195 */
        OAK_LOG(VariantTextureMaker.createBlockType("oakLog", "wood/oak-log.png", ShapeList.COLUMN)),
        WHITE_LOG(VariantTextureMaker.createBlockType("whiteLog", "wood/white-log.png", ShapeList.COLUMN)),
        ACACIA_STAIRS_LEFT(new BlockType("acaciaStairs1",
                        new Texture[] { new Texture(ShapeList.STAIR1,
                                        PathManager.loadImage("wood/woodStairs/wood-acacia-stairs1.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        ACACIA_STAIRS_RIGHT(new BlockType("acaciaStairs2",
                        new Texture[] { new Texture(ShapeList.STAIR2,
                                        PathManager.loadImage("wood/woodStairs/wood-acacia-stairs2.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        OAK_STAIRS_LEFT(new BlockType("oakStairs1",
                        new Texture[] { new Texture(ShapeList.STAIR1,
                                        PathManager.loadImage("wood/woodStairs/wood-oak-stairs1.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        /* 200 */
        OAK_STAIRS_RIGHT(new BlockType("oakStairs2",
                        new Texture[] { new Texture(ShapeList.STAIR2,
                                        PathManager.loadImage("wood/woodStairs/wood-oak-stairs2.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        PINE_STAIRS_LEFT(new BlockType("pineStairs1",
                        new Texture[] { new Texture(ShapeList.STAIR1,
                                        PathManager.loadImage("wood/woodStairs/wood-pine-stairs1.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        PINE_STAIRS_RIGHT(new BlockType("pineStairs2",
                        new Texture[] { new Texture(ShapeList.STAIR2,
                                        PathManager.loadImage("wood/woodStairs/wood-pine-stairs2.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        WHITE_STAIRS_LEFT(new BlockType("whiteStairs1",
                        new Texture[] { new Texture(ShapeList.STAIR1,
                                        PathManager.loadImage("wood/woodStairs/wood-white-stairs1.png")) },
                        new Collision[] { CollisionList.STAIR1 },
                        null,
                        null)),
        WHITE_STAIRS_RIGHT(new BlockType("whiteStairs2",
                        new Texture[] { new Texture(ShapeList.STAIR2,
                                        PathManager.loadImage("wood/woodStairs/wood-white-stairs2.png")) },
                        new Collision[] { CollisionList.STAIR2 },
                        null,
                        null)),
        /* 205 */
        COLUMN(new BlockType("column",
                        new Texture[] { new Texture(ShapeList.COLUMN,
                                        PathManager.loadImage("column.png")) },
                        new Collision[] { CollisionList.COLUMN },
                        null,
                        null)),
        WHITE_COLUMN(new BlockType("whiteColumn",
                        new Texture[] { new Texture(ShapeList.COLUMN,
                                        PathManager.loadImage("white-column.png")) },
                        new Collision[] { CollisionList.COLUMN },
                        null,
                        null)),
        FRAME_LEFT(new BlockType("frameLeft",
                        new Texture[] { new Texture(ShapeList.INSIDE,
                                        PathManager.loadImage("frame-left.png")) },
                        null,
                        new Property[] {new Property(PropertyList.NO_COLLISION), new Property("floor")},
                        new BlockBehavior[] { new BlockBehaviorText() })),
        FRAME_RIGHT(new BlockType("frameRight",
                        new Texture[] { new Texture(ShapeList.INSIDE,
                                        PathManager.loadImage("frame-right.png")) },
                        null,
                        new Property[] {new Property(PropertyList.NO_COLLISION), new Property("floor")},
                        new BlockBehavior[] { new BlockBehaviorText() })),
        LIAN_LEFT(new BlockType("lianLeft",
                        new Texture[] { new Texture(ShapeList.INSIDE,
                                        PathManager.loadImage("lian-left.png")) },
                        null,
                        new Property[] {new Property(PropertyList.NO_COLLISION), new Property(PropertyList.BURNABLE)},
                        null)),
        /* 210 */
        LIAN_RIGHT(new BlockType("lianRight",
                        new Texture[] { new Texture(ShapeList.INSIDE,
                                        PathManager.loadImage("lian-right.png")) },
                        null,
                        new Property[] {new Property(PropertyList.NO_COLLISION), new Property(PropertyList.BURNABLE)},
                        null)),
        ACACIA_STAIRS_3(new BlockType("acaciaStairs3",
                        new Texture[] { new Texture(ShapeList.STAIR3,
                                        PathManager.loadImage("wood/woodStairs/wood-acacia-stairs3.png")) },
                        new Collision[] { CollisionList.STAIR3 },
                        null,
                        null)),
        ACACIA_STAIRS_4(new BlockType("acaciaStairs4",
                        new Texture[] { new Texture(ShapeList.STAIR4,
                                        PathManager.loadImage("wood/woodStairs/wood-acacia-stairs4.png")) },
                        new Collision[] { CollisionList.STAIR4 },
                        null,
                        null)),
        OAK_STAIRS_3(new BlockType("oakStairs3",
                        new Texture[] { new Texture(ShapeList.STAIR3,
                                        PathManager.loadImage("wood/woodStairs/wood-oak-stairs3.png")) },
                        new Collision[] { CollisionList.STAIR3 },
                        null,
                        null)),
        OAK_STAIRS_4(new BlockType("oakStairs4",
                        new Texture[] { new Texture(ShapeList.STAIR4,
                                        PathManager.loadImage("wood/woodStairs/wood-oak-stairs4.png")) },
                        new Collision[] { CollisionList.STAIR4 },
                        null,
                        null)),
        /* 215 */
        PINE_STAIRS_3(new BlockType("pineStairs3",
                        new Texture[] { new Texture(ShapeList.STAIR3,
                                        PathManager.loadImage("wood/woodStairs/wood-pine-stairs3.png")) },
                        new Collision[] { CollisionList.STAIR3 },
                        null,
                        null)),
        PINE_STAIRS_4(new BlockType("pineStairs4",
                        new Texture[] { new Texture(ShapeList.STAIR4,
                                        PathManager.loadImage("wood/woodStairs/wood-pine-stairs4.png")) },
                        new Collision[] { CollisionList.STAIR4 },
                        null,
                        null)),
        WHITE_STAIRS_3(new BlockType("whiteStairs3",
                        new Texture[] { new Texture(ShapeList.STAIR3,
                                        PathManager.loadImage("wood/woodStairs/wood-white-stairs3.png")) },
                        new Collision[] { CollisionList.STAIR3 },
                        null,
                        null)),
        WHITE_STAIRS_4(new BlockType("whiteStairs4",
                        new Texture[] { new Texture(ShapeList.STAIR4,
                                        PathManager.loadImage("wood/woodStairs/wood-white-stairs4.png")) },
                        new Collision[] { CollisionList.STAIR4 },
                        null,
                        null)),
        GRID_LEFT(new BlockType("gridLeft",
                        new Texture[] { new Texture(ShapeList.BORDER_LEFT,
                                        PathManager.loadImage("grids/grid-left.png")) },
                        new Collision[] { CollisionList.BARRIER_LEFT },
                        null,
                        null)),
        /* 220 */
        GRID_RIGHT(new BlockType("gridRight",
                        new Texture[] { new Texture(ShapeList.BORDER_RIGHT,
                                        PathManager.loadImage("grids/grid-right.png")) },
                        new Collision[] { CollisionList.BARRIER_RIGHT },
                        null,
                        null)),
        GRID_HORIZONTAL(new BlockType("gridHorizontal",
                        new Texture[] { new Texture(ShapeList.BORDER_HORIZONTAL,
                                        PathManager.loadImage("grids/grid-horizontal.png")) },
                        new Collision[] { CollisionList.BARRIER_HORIZONTAL },
                        null,
                        null)),
        ;

        public final BlockType blockType;

        BlockTemplate(BlockType blockType) {
                this.blockType = blockType;
        }

        public static String toString(BlockTemplate[] blockTypes) {
                String res = "";
                for (int i = 0; i < blockTypes.length; i++)
                        res += i + " " + blockTypes[i].blockType.getName() + "\n";
                return res;
        }
}
